Rest api
elkarbackup/elkarbackup pull request #475
Opened 2021-04-19 13:23 UTC by uanabitarte

2021-04-20 10:23 UTC, elacunza commented
Uxue, bi detaile nagusi ikusten ditut:
- Kode komentatua ez genuke igo beharko
- Klase berrien aldagai eta metodoak alfabetikoki ordenatu behar ditugu, kode estiloaren arabera (3.6 puntua), konstruktorea izan ezik.

2021-04-22 14:25 UTC, elacunza requested changes
Thanks a lot Uxue, overall seems very good works although I haven't taken a change to test it. Let's squash latest style comments and merge it to master.

Also, sorry for being so picky about style and order, but fixing those things afterwards is a git history hell.

2021-04-22 14:25 UTC, elacunza commented on src/Api/DataTransformers/JobInputDataTransformer.php
> +    }
Those 3 methods seem out of order

2021-04-22 14:25 UTC, elacunza commented on src/Api/Dto/JobOutput.php
> +    }
Should be sooner in the file

2021-04-22 14:25 UTC, elacunza commented on src/Api/Dto/UserOutput.php
> +    private $username;
should be after roles

2021-04-22 14:25 UTC, elacunza commented on src/Api/Dto/UserOutput.php
> +    }
move after getRoles

2021-04-22 14:25 UTC, elacunza commented on src/Api/Dto/UserOutput.php
> +    }
Move after setRoles

2021-04-22 14:25 UTC, elacunza commented on src/Api/DataTransformers/JobInputDataTransformer.php
> +
Should go after setNotificationsEmail

2021-04-22 14:25 UTC, elacunza commented on src/Controller/DefaultController.php
> +                    array('%clientId%' => $id),
This message is for the user in WUI, I think we should keep using client name so that it is gentler for the user.

2021-04-22 14:25 UTC, elacunza commented on src/Controller/DefaultController.php
> +                    ),
Should be one indentation less?

2021-04-22 14:25 UTC, elacunza commented on src/Controller/DefaultController.php
> +                    ),
Should be one indentation less?

2021-04-23 08:09 UTC, elacunza commented
Seems good for the size of the modifications so far.
Is src/Api/DataProviders/JobSubresourceDataProvider.php needed anymore, as where're treating it as Item and not a subresource?

2021-04-23 08:11 UTC, uanabitarte commented
No, it is not needed anymore, I forgot to remove it. I have removed it in the next commit

2021-04-23 08:35 UTC, elacunza commented
Ok push it. Do you think API is usable as it is right now?

2021-04-23 09:31 UTC, uanabitarte commented
Yes, I think now it should be usable

2021-04-23 09:41 UTC, elacunza commented
Ok thanks, let's merge this as the first alpha version! I will squash all merges to one so that we don't have all the reordering commits in the main tree.

2021-04-23 09:43 UTC, merged