Add French translation
elkarbackup/elkarbackup pull request #539
Opened 2021-05-05 21:20 UTC by jvies

hi all,

I've just discovered Elkarbackup a few days ago. It matches my expectation for a web based GUI around RSYNC (that I use since years for my backups).

Here is a PR to add the French translation. It think it needs to be reviewed by another french speaker if you have one around here.

2021-05-06 06:07 UTC, elacunza commented
Thanks for your contribution! Let's see whether @xezpeleta can review the translation, otherwise we can merge and fix later if necessary.

2021-05-06 19:43 UTC, xezpeleta commented
Bonjour Jérémy,

Nous allons jeter un oeil et nous vous tiendrons au courant

Merci beaucoup!

2021-05-06 20:03 UTC, jvies commented
Bonjour,

j'ai laissé "backup" et pas "sauvegarde" partout.

N'hésitez pas à me faire des remarques, je peux y consacrer quelques heures
à l'occasion !

Le jeu. 6 mai 2021 à 21:44, Xabi ***@***.***> a écrit :

> Bonjour Jérémy,
>
> Nous allons jeter un oeil et nous vous tiendrons au courant
>
> Merci beaucoup!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elkarbackup/elkarbackup/pull/539#issuecomment-833810778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABB6RVZ7M7TNVT2SVAOB5YDTMLWQJANCNFSM44FY5YDQ>
> .
>

2021-05-06 20:21 UTC, xezpeleta requested changes
Thank you very much for your contribution. You did a great job.

I think we should keep this PR only for french translations. It would be nice to have the other changes (english corrections etc) in a separate PR.

Merci beaucoup!!!

2021-05-06 20:21 UTC, xezpeleta commented on translations/BinovoElkarBackup.fr.yml
> + Choisissze le nombre de lignes que vous voulez afficher par page
Choisissez :)

2021-05-06 20:21 UTC, xezpeleta commented on templates/default/client.html.twig
> +                <a class="collapsed" href="#viewadvanced" data-toggle="collapse" data-target="#viewadvanced">{% trans %}Advanced{% endtrans %}</a></div>
Hi! This correction is not related to the french translation.
Could you use a separate PR for these changes? Thanks!

2021-05-06 20:21 UTC, xezpeleta commented on templates/default/job.html.twig
> +                    <a class="collapsed" href="#viewadvanced" data-toggle="collapse" data-target="#viewadvanced">{% trans %}Advanced{% endtrans %}</a></div>
Same here. I think it's better to keep this changes in a separate PR

2021-05-06 20:21 UTC, xezpeleta commented on translations/BinovoElkarBackup.en.yml
> + <h4>Yearly</h4>
Fixed English translations. Can I ask you a separate PR? Thanks

2021-05-07 17:19 UTC, xezpeleta approved these changes

2021-05-07 17:25 UTC, xezpeleta commented
> Bonjour, j'ai laissé "backup" et pas "sauvegarde" partout. N'hésitez pas à me faire des remarques, je peux y consacrer quelques heures à l'occasion !

Parfait! Nous avons fait exactement la même chose en basque et en espagnol.

Merci beaucoup encore

2021-05-07 17:25 UTC, merged